`r paste0('# ', country, '{data-navmenu="Individual Country Reports"}')`



Column
------------------------

#### `r paste0(country, " report")`

### Batch progression in the scanned amounts

```{r}
ind_count_batc_prog <- subpage_data |> 
  group_by(batch) |> 
  summarise(total_bottles = sum(bottle_count)) |> 
  ggplot(aes(batch,total_bottles)) +
  geom_col(fill = "aquamarine4") +
  geom_line(aes(group = 1)) +
  geom_point()  +
      labs(x = "", y = "") +
  coord_cartesian(expand = T,
                  clip = "off") +
  scale_y_continuous(labels = scales::comma,
                     breaks = seq(0,200000, 10000))+
  geom_label(aes(label = total_bottles),
             nudge_y = 5000,
             label.size = 1,
             size = 7) + 
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(face = "bold",
                               size = 13,
                               vjust = 0.5),
    axis.ticks = element_blank(),
    axis.line = element_blank()
  )
ggplotly(ind_count_batc_prog)
```



Column
------------


### Distribution of the product category and bottle count reported

```{r}
# bar plot of product category and bottlecount

ind_produc_cat <- subpage_data |>
  nest(data = -product_category) |> 
  mutate(total_bottles = map_dbl(data,~ sum(.$bottle_count))) |> 
  arrange(desc(total_bottles)) |> 
  mutate(product_category = fct_reorder(product_category, total_bottles)) |> 
  unnest(cols = c(data)) |> 
  ggplot(aes(total_bottles, product_category, fill = amount_rec)) + 
  geom_col()
ggplotly(ind_produc_cat)
```


### Top 20 brands found

```{r}
ind_count_top_brands <- subpage_data |> 
  group_by(brand_name) |> 
  summarise(total_bottles = sum(bottle_count)) |> 
  arrange(desc(total_bottles)) |> 
  head(n = 20) |> 
  mutate(brand_name = fct_reorder(brand_name, total_bottles)) |> 
  ggplot(aes(total_bottles,brand_name)) +
  geom_col(fill = "aquamarine4")
ggplotly(ind_count_top_brands)



```
