---
title: "Waste dataviz 1"
author: "Peter Boshe"
date: "01/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', collapse = TRUE, echo = FALSE, message = FALSE)
```



```{r}
# Packages
library(tidyverse)
# library(gghighlight)
library(ggtext)
library(patchwork)
# library(showtext)

# Parameters
  #input
file_raw <- here::here("data/clean_waste_base_data.rds")
  #output
file_out <- here::here("docs/dataviz.png")
# theme update

theme_set(theme_classic())

# colors

water_color <- "#016fb9"
soft_color <- "#ff9505"
energy_color <- "#ec4e20"

# import fonts

# font_add_google('Lora', 'lora')
# font_add_google('Fira Sans', 'firasans')
# font_add_google('Dosis', 'dosis')
# showtext_auto()

```



```{r}
df <- read_rds(file_raw)

## Recoding df$product_category into df$product_category_rec
df$product_category_rec <- df$product_category %>%
  fct_recode(
    "juices and punches" = "juice",
    "energy drinks" = "energy drink",
    "carbonated drinks" = "carbonated drink"
  )

## Recoding df$month into df$month_rec
df$month_rec <- df$month %>%
  fct_recode(
    "Jan" = "01",
    "Feb" = "02",
    "Mar" = "03",
    "Apr" = "04",
    "May" = "05",
    "Jun" = "06",
    "Jul" = "07",
    "Aug" = "08",
    "Sep" = "09",
    "Oct" = "10",
    "Nov" = "11",
    "Dec" = "12"
  )

df |> 
  group_by(year, month_rec, product_category_rec) |> 
  summarise(total_bottles = sum(bottle_count)) |> ## Reordering df$product_category
  mutate(
    product_category_rec = fct_reorder(product_category_rec, total_bottles, .desc = T),
    color_dat = fct_inorder(case_when(
    product_category_rec == "water" ~ water_color,
    product_category_rec == "carbonated drinks" ~ soft_color,
    product_category_rec == "energy drinks" ~ energy_color,
    TRUE ~ "darkgrey"
  ))) -> colored_data

## Reordering colored_data$product_category_rec
colored_data$product_category_rec <- colored_data$product_category_rec %>%
  fct_relevel(
    "domestic products", "food products", "unknown", "juices and punches",
    "hard liquor", "beer", "energy drinks", "carbonated drinks",
    "water"
  )



glimpse(colored_data)

  ggplot(colored_data, aes(month_rec,total_bottles, group = product_category_rec)) +
  geom_col(fill = colored_data$color_dat,
           color = "white") +
  facet_wrap( ~ year) +
  labs(
       y = "TOTAL BOTTLES SCANNED",
       x = "") -> p
```



```{r}
# HACK annotating individual facets

label_text <- data.frame(year = c(2021, 2021, 2022), 
                         label = c("while more than 70% of the<br>waste scanned were <br>plastic bottles of 1 litre<br>and below.","<span style='color:#016fb9'><strong>Water</strong></span>, <span style='color:#ff9505'><strong>soft(carbonated)drinks</strong></span><br>and <span style='color:#ec4e20'><strong>energy drinks</strong></span> products<br> contributed to more than <br>85% of total waste scanned,","Although we also <br>had other product <br>categories like;<br> - hard liquor,<br> - juices&punches,<br> - domestic products,<br> -food products,<br> and others...<br>they were not as <br>abundant as their <br>counterparts<br>highlighted."),
                         month_rec = c(7.7,7.7,13.5),
                         total_bottles = c(110000,170000,90000),
                         product_category_rec = c("","",""),
                         hjust = c("middle","middle","right")) # HACK this line was needed to silence error

segment_df <- data.frame(x = 4.5, 
                 y = 155000,
                 xend = 7.5,
                 yend = 150000,
                 year = 2022,
                 product_category_rec = "")

title_text <- "Can't we handle our thirst-quenchers better?"
subtitle_text <- "The total plastic bottles scanned has been rising steadily since the project began<br>on March, 2021.<br>Do we need alternative packaging or just better waste management?"
caption_text <- "data source:wastebase.org<br>author:Peter Boshe <span style='color:#016fb9'>peterboshe.netlify.app</span>"


p + theme(
    panel.background = element_rect(fill = "cornsilk"),
    plot.background = element_rect(fill = "cornsilk"),
    # panel.background = element_blank(),
    axis.text.y = element_text(colour = "darkgrey",
                            size = 10),
    axis.text.x = element_text(colour = "darkgrey",
                               size = 9),
    axis.line.y = element_blank(),
    axis.line.x = element_line(colour = "darkgrey"),
    axis.ticks.x = element_line(colour = "darkgrey"),
    axis.ticks.y = element_blank(),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text = element_text(colour = "red",
                              hjust = 0,
                              face = "bold",
                              size = 11),
    axis.title.y = element_text(colour = "darkgrey",
                                hjust = 1),
    plot.title.position = "plot",
    title = element_blank()
  ) +
  scale_x_discrete(position = "top") +
  scale_y_continuous(breaks = seq(0,200000,10000),
                    limits = c(0,200000),
                    labels = scales::comma) +
  geom_curve(data = segment_df,aes(x = x, 
                 y = y,
                 xend = xend,
                 yend = yend), 
             curvature = -0.2,
             angle = 120, 
             ncp = 5,
             color = "darkgrey",
             arrow = arrow(angle = 30, 
                           length = unit(0.2, "cm"), 
                           ends = "first", 
                           type = "open")) +
  geom_richtext(data = label_text,
            aes(x = month_rec, y = total_bottles, 
                label = label, hjust = hjust),
            label.color = NA,
            fill = NA,
            size = 5,
            family = 'wqy-microhei') +
  coord_cartesian(expand = F,
                  clip = "off") +
  plot_annotation(
    title = title_text,
    # subtitle = subtitle_text,
    caption = caption_text,
    theme = theme(
      # plot.title = element_markdown(
      #   # margin = margin(b = 0.4, unit = 'cm'),
      #   # 0.4cm margin at bottom of title
      #   size = 16,
      #   colour = "#016fb9",
      #   linewidth = 6
      # ),
      plot.title = element_textbox_simple(
       size = 16,
      lineheight = 1,
      padding = margin(5.5, 5.5, 5.5, 5.5),
      margin = margin(0, 0, 5.5, 0),
      fill = "cornsilk",
      colour = "#016fb9"),
      # plot.subtitle = element_markdown(
      #   size = 13
      # ),
      plot.caption.position = 'plot',
      plot.caption = element_markdown(
        hjust = 0, 
        size = 9, 
        colour = "darkgrey", 
        lineheight = 1.25
      ),
      plot.background = element_rect(fill = 'cornsilk', colour = NA)
      # This is only a trick to make sure that background really is white
      # Otherwise, some browsers or photo apps will apply a dark mode
    )
  )
  
ggsave(file_out, width = 800, height = 400, units = "px", dpi = "screen")

```

